type Exercise {
  name: String! @unique
  category: String!
  bodypart: String!
}

type WorkoutExercise {
  name: String!
  reps: Int!
  sets: Int!
  weight: Int!
  rest: Int
}

type Workout {
  name: String! @unique
  exercises: [WorkoutExercise!]
}

type Query {
  exercises: [Exercise!]
  workouts: [Workout]
}
