type User {
  username: String!
  email: String!
  exercises: [ExerciseData] @relation
  workouts: [Workout] @relation
}

type ExerciseData {
  user: User!
  name: String! @unique
  category: String!
  bodypart: String!
}

type Set @embedded {
  reps: Int!
  weight: Int!
  rest: Int
}

type Exercise {
  exerciseData: ExerciseData!
  workout: Workout!
  sets: [Set!]!
}

type Workout {
  user: User!
  name: String! @unique
  exercises: [Exercise!]! @relation
}

type Query {
  allUsers: [User]
  allExercises: [ExerciseData]
  allWorkouts: [Workout]
}
