type User {
  authSub: String!
  username: String!
  email: String!
  exercises: [ExerciseData] @relation
  workouts: [Workout] @relation
}

type ExerciseData {
  user: User
  name: String!
  category: String!
  bodypart: String!
}

type Set @embedded {
  reps: Int!
  weight: Float!
  rest: Int
}

type Exercise @embedded {
  exerciseData: ID!
  name: String!
  sets: [Set!]!
}

type Workout {
  user: User!
  name: String!
  exercises: [Exercise!]!
}

type CompletedWorkout {
  workout: Workout!
  date: Date!
  time: String!
  timeTaken: String!
}

type Query {
  allUsers: [User]
  allExercises: [ExerciseData]
  allWorkouts: [Workout]
  getUserByAuthSub(authSub: String!): User
}
